### ISSUE TITLE
Github Pages - Readme.me - Descrição do projeto

### ISSUE THREAD

**Issue by LeandroGazoli** [Jeandra/Cronometro#1]
Vamos lá, temos algumas coisas faltando no seu projeto para melhor descrever o  que você fez, o projeto eu olhei está legal e funcionando, responsivo (Otimo), porrem percebi que você montou o github pages porem não deixou facil para acessar o projeto.

segue um print da parte mais importante do seu projeto.

![image](https://user-images.githubusercontent.com/73295202/231832247-482f585e-c87b-4edd-9097-428c016614c4.png)

percebe que não colocou o link para navegar até o sistema. Isso atrapalha quando alguem vai observar o seu projeto, ali em about coloque a descrição/link da pagina no github pages, com isso você ajuda aos analistas que veem seu perfil acessar o projeto de forma mais facil.

Outra coisa se possivel coloque no readme uma breve descrição do projeto, exemplo Projeto Cronometro. desenvolvido com as tecnologias tal, que foi aprendida ou apresentada pelo curso tal, ou fala que foi um projeto que realizou para melhorar seu conhecimento com as tecnologias etc....

#documentation

**Comment by Jeandra** [comment]
Valeu pelas dicas e sugestões, vou colocar em prática. 🚀🚀
